version: "3"
services:
  db:
    container_name: db
    build: db/
    image: db:latest
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - djangonetwork
  web:
    build: web/
    image: web:latest
    ports:
      - 8080:8080
    networks:
      - djangonetwork
  api:
    build: api/
    image: api:latest
    links:
      - db:db
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - djangonetwork
networks:
  djangonetwork:
    driver: bridge