@startuml
!define LIGHTBLUE
!includeurl https://gist.githubusercontent.com/amgs/de57560012a8a5f0e4240f392b678a40/raw/c43f948dd1f23ed1b87c6c9fc972e71493859b16/style.puml
hide circle
hide empty methods

entity Publisher {
    *id [PK]: INT
    *name:TEXT
    *city:TEXT
    *country:TEXT
    *website:URL
}

entity Game {
    *id [PK]: INT
    *title: TEXT
    *pub_date: DATE
    *genre: TEXT
    *price: DECIMAL
    *publisher_id [FK]: INT
}

Publisher ||--|{ Game

@enduml