apiVersion: v1
kind: Service
metadata:
  name: project-db-svc
  labels:
    app: project-db-statefulset
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: project-db-statefulset
---
apiVersion: v1
kind: Service
metadata:
  name: "db"
spec:
  type: ExternalName
  externalName: "project-db-st-0.project-db-svc.default.svc.cluster.local"
